# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2016-12-03 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teamplayer', '0005_move_libraryitem_to_teamplayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teamplayer.LibraryItem')),
            ],
        ),
    ]
